/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as ParticipationGuideRouteImport } from './routes/participation-guide'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LabRouteImport } from './routes/lab'
import { Route as HelpMeChooseRouteImport } from './routes/help-me-choose'
import { Route as EducationSupportRouteImport } from './routes/education-support'
import { Route as CommunitySupportRouteImport } from './routes/community-support'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ToolsProjectIdRouteImport } from './routes/tools.$projectId'
import { Route as SettingsFamilyRouteImport } from './routes/settings.family'
import { Route as SettingsAddEventRouteImport } from './routes/settings.add-event'
import { Route as LearnerIdRouteImport } from './routes/learner.$id'
import { Route as LabWeavingRouteImport } from './routes/lab.weaving'
import { Route as LabVisualRouteImport } from './routes/lab.visual'
import { Route as LabStationsRouteImport } from './routes/lab.stations'
import { Route as LabStatesRouteImport } from './routes/lab.states'
import { Route as LabStartRouteImport } from './routes/lab.start'
import { Route as LabRoutineRouteImport } from './routes/lab.routine'
import { Route as LabParticipationsRouteImport } from './routes/lab.participations'
import { Route as LabCommunityRouteImport } from './routes/lab.community'
import { Route as LabAiRouteImport } from './routes/lab.ai'
import { Route as ActivitiesOptionsRouteImport } from './routes/activities.options'
import { Route as ActivitiesMyDayRouteImport } from './routes/activities.my-day'
import { Route as ActivitiesLevelRouteImport } from './routes/activities.level'
import { Route as ActivitiesBrowseRouteImport } from './routes/activities.browse'
import { Route as ActivitiesCategoryRouteImport } from './routes/activities.$category'
import { Route as AuthenticatedMyRoutineRouteImport } from './routes/_authenticated/my-routine'
import { Route as AuthenticatedActiveParticipationsRouteImport } from './routes/_authenticated/active-participations'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LabEventEventIdRouteImport } from './routes/lab.event.$eventId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipationGuideRoute = ParticipationGuideRouteImport.update({
  id: '/participation-guide',
  path: '/participation-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpMeChooseRoute = HelpMeChooseRouteImport.update({
  id: '/help-me-choose',
  path: '/help-me-choose',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationSupportRoute = EducationSupportRouteImport.update({
  id: '/education-support',
  path: '/education-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySupportRoute = CommunitySupportRouteImport.update({
  id: '/community-support',
  path: '/community-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsProjectIdRoute = ToolsProjectIdRouteImport.update({
  id: '/tools/$projectId',
  path: '/tools/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFamilyRoute = SettingsFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAddEventRoute = SettingsAddEventRouteImport.update({
  id: '/add-event',
  path: '/add-event',
  getParentRoute: () => SettingsRoute,
} as any)
const LearnerIdRoute = LearnerIdRouteImport.update({
  id: '/learner/$id',
  path: '/learner/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabWeavingRoute = LabWeavingRouteImport.update({
  id: '/weaving',
  path: '/weaving',
  getParentRoute: () => LabRoute,
} as any)
const LabVisualRoute = LabVisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => LabRoute,
} as any)
const LabStationsRoute = LabStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => LabRoute,
} as any)
const LabStatesRoute = LabStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => LabRoute,
} as any)
const LabStartRoute = LabStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => LabRoute,
} as any)
const LabRoutineRoute = LabRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => LabRoute,
} as any)
const LabParticipationsRoute = LabParticipationsRouteImport.update({
  id: '/participations',
  path: '/participations',
  getParentRoute: () => LabRoute,
} as any)
const LabCommunityRoute = LabCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => LabRoute,
} as any)
const LabAiRoute = LabAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => LabRoute,
} as any)
const ActivitiesOptionsRoute = ActivitiesOptionsRouteImport.update({
  id: '/activities/options',
  path: '/activities/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesMyDayRoute = ActivitiesMyDayRouteImport.update({
  id: '/activities/my-day',
  path: '/activities/my-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesLevelRoute = ActivitiesLevelRouteImport.update({
  id: '/activities/level',
  path: '/activities/level',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesBrowseRoute = ActivitiesBrowseRouteImport.update({
  id: '/activities/browse',
  path: '/activities/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesCategoryRoute = ActivitiesCategoryRouteImport.update({
  id: '/activities/$category',
  path: '/activities/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRoutineRoute = AuthenticatedMyRoutineRouteImport.update({
  id: '/my-routine',
  path: '/my-routine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActiveParticipationsRoute =
  AuthenticatedActiveParticipationsRouteImport.update({
    id: '/active-participations',
    path: '/active-participations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LabEventEventIdRoute = LabEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => LabRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community-support': typeof CommunitySupportRoute
  '/education-support': typeof EducationSupportRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/lab': typeof LabRouteWithChildren
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/participation-guide': typeof ParticipationGuideRoute
  '/reminder': typeof ReminderRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/active-participations': typeof AuthenticatedActiveParticipationsRoute
  '/my-routine': typeof AuthenticatedMyRoutineRoute
  '/activities/$category': typeof ActivitiesCategoryRoute
  '/activities/browse': typeof ActivitiesBrowseRoute
  '/activities/level': typeof ActivitiesLevelRoute
  '/activities/my-day': typeof ActivitiesMyDayRoute
  '/activities/options': typeof ActivitiesOptionsRoute
  '/lab/ai': typeof LabAiRoute
  '/lab/community': typeof LabCommunityRoute
  '/lab/participations': typeof LabParticipationsRoute
  '/lab/routine': typeof LabRoutineRoute
  '/lab/start': typeof LabStartRoute
  '/lab/states': typeof LabStatesRoute
  '/lab/stations': typeof LabStationsRoute
  '/lab/visual': typeof LabVisualRoute
  '/lab/weaving': typeof LabWeavingRoute
  '/learner/$id': typeof LearnerIdRoute
  '/settings/add-event': typeof SettingsAddEventRoute
  '/settings/family': typeof SettingsFamilyRoute
  '/tools/$projectId': typeof ToolsProjectIdRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/lab/': typeof LabIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lab/event/$eventId': typeof LabEventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community-support': typeof CommunitySupportRoute
  '/education-support': typeof EducationSupportRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/participation-guide': typeof ParticipationGuideRoute
  '/reminder': typeof ReminderRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/active-participations': typeof AuthenticatedActiveParticipationsRoute
  '/my-routine': typeof AuthenticatedMyRoutineRoute
  '/activities/$category': typeof ActivitiesCategoryRoute
  '/activities/browse': typeof ActivitiesBrowseRoute
  '/activities/level': typeof ActivitiesLevelRoute
  '/activities/my-day': typeof ActivitiesMyDayRoute
  '/activities/options': typeof ActivitiesOptionsRoute
  '/lab/ai': typeof LabAiRoute
  '/lab/community': typeof LabCommunityRoute
  '/lab/participations': typeof LabParticipationsRoute
  '/lab/routine': typeof LabRoutineRoute
  '/lab/start': typeof LabStartRoute
  '/lab/states': typeof LabStatesRoute
  '/lab/stations': typeof LabStationsRoute
  '/lab/visual': typeof LabVisualRoute
  '/lab/weaving': typeof LabWeavingRoute
  '/learner/$id': typeof LearnerIdRoute
  '/settings/add-event': typeof SettingsAddEventRoute
  '/settings/family': typeof SettingsFamilyRoute
  '/tools/$projectId': typeof ToolsProjectIdRoute
  '/activities': typeof ActivitiesIndexRoute
  '/lab': typeof LabIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lab/event/$eventId': typeof LabEventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community-support': typeof CommunitySupportRoute
  '/education-support': typeof EducationSupportRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/lab': typeof LabRouteWithChildren
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/participation-guide': typeof ParticipationGuideRoute
  '/reminder': typeof ReminderRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/active-participations': typeof AuthenticatedActiveParticipationsRoute
  '/_authenticated/my-routine': typeof AuthenticatedMyRoutineRoute
  '/activities/$category': typeof ActivitiesCategoryRoute
  '/activities/browse': typeof ActivitiesBrowseRoute
  '/activities/level': typeof ActivitiesLevelRoute
  '/activities/my-day': typeof ActivitiesMyDayRoute
  '/activities/options': typeof ActivitiesOptionsRoute
  '/lab/ai': typeof LabAiRoute
  '/lab/community': typeof LabCommunityRoute
  '/lab/participations': typeof LabParticipationsRoute
  '/lab/routine': typeof LabRoutineRoute
  '/lab/start': typeof LabStartRoute
  '/lab/states': typeof LabStatesRoute
  '/lab/stations': typeof LabStationsRoute
  '/lab/visual': typeof LabVisualRoute
  '/lab/weaving': typeof LabWeavingRoute
  '/learner/$id': typeof LearnerIdRoute
  '/settings/add-event': typeof SettingsAddEventRoute
  '/settings/family': typeof SettingsFamilyRoute
  '/tools/$projectId': typeof ToolsProjectIdRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/lab/': typeof LabIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lab/event/$eventId': typeof LabEventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/community-support'
    | '/education-support'
    | '/help-me-choose'
    | '/lab'
    | '/mcp'
    | '/messages'
    | '/participation-guide'
    | '/reminder'
    | '/resources'
    | '/search'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/active-participations'
    | '/my-routine'
    | '/activities/$category'
    | '/activities/browse'
    | '/activities/level'
    | '/activities/my-day'
    | '/activities/options'
    | '/lab/ai'
    | '/lab/community'
    | '/lab/participations'
    | '/lab/routine'
    | '/lab/start'
    | '/lab/states'
    | '/lab/stations'
    | '/lab/visual'
    | '/lab/weaving'
    | '/learner/$id'
    | '/settings/add-event'
    | '/settings/family'
    | '/tools/$projectId'
    | '/activities/'
    | '/lab/'
    | '/tools/'
    | '/.mcp/invoke-tool/$tool'
    | '/lab/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/community-support'
    | '/education-support'
    | '/help-me-choose'
    | '/mcp'
    | '/messages'
    | '/participation-guide'
    | '/reminder'
    | '/resources'
    | '/search'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/active-participations'
    | '/my-routine'
    | '/activities/$category'
    | '/activities/browse'
    | '/activities/level'
    | '/activities/my-day'
    | '/activities/options'
    | '/lab/ai'
    | '/lab/community'
    | '/lab/participations'
    | '/lab/routine'
    | '/lab/start'
    | '/lab/states'
    | '/lab/stations'
    | '/lab/visual'
    | '/lab/weaving'
    | '/learner/$id'
    | '/settings/add-event'
    | '/settings/family'
    | '/tools/$projectId'
    | '/activities'
    | '/lab'
    | '/tools'
    | '/.mcp/invoke-tool/$tool'
    | '/lab/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendar'
    | '/community-support'
    | '/education-support'
    | '/help-me-choose'
    | '/lab'
    | '/mcp'
    | '/messages'
    | '/participation-guide'
    | '/reminder'
    | '/resources'
    | '/search'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/active-participations'
    | '/_authenticated/my-routine'
    | '/activities/$category'
    | '/activities/browse'
    | '/activities/level'
    | '/activities/my-day'
    | '/activities/options'
    | '/lab/ai'
    | '/lab/community'
    | '/lab/participations'
    | '/lab/routine'
    | '/lab/start'
    | '/lab/states'
    | '/lab/stations'
    | '/lab/visual'
    | '/lab/weaving'
    | '/learner/$id'
    | '/settings/add-event'
    | '/settings/family'
    | '/tools/$projectId'
    | '/activities/'
    | '/lab/'
    | '/tools/'
    | '/.mcp/invoke-tool/$tool'
    | '/lab/event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CommunitySupportRoute: typeof CommunitySupportRoute
  EducationSupportRoute: typeof EducationSupportRoute
  HelpMeChooseRoute: typeof HelpMeChooseRoute
  LabRoute: typeof LabRouteWithChildren
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  ParticipationGuideRoute: typeof ParticipationGuideRoute
  ReminderRoute: typeof ReminderRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ActivitiesCategoryRoute: typeof ActivitiesCategoryRoute
  ActivitiesBrowseRoute: typeof ActivitiesBrowseRoute
  ActivitiesLevelRoute: typeof ActivitiesLevelRoute
  ActivitiesMyDayRoute: typeof ActivitiesMyDayRoute
  ActivitiesOptionsRoute: typeof ActivitiesOptionsRoute
  LearnerIdRoute: typeof LearnerIdRoute
  ToolsProjectIdRoute: typeof ToolsProjectIdRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participation-guide': {
      id: '/participation-guide'
      path: '/participation-guide'
      fullPath: '/participation-guide'
      preLoaderRoute: typeof ParticipationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-me-choose': {
      id: '/help-me-choose'
      path: '/help-me-choose'
      fullPath: '/help-me-choose'
      preLoaderRoute: typeof HelpMeChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-support': {
      id: '/education-support'
      path: '/education-support'
      fullPath: '/education-support'
      preLoaderRoute: typeof EducationSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-support': {
      id: '/community-support'
      path: '/community-support'
      fullPath: '/community-support'
      preLoaderRoute: typeof CommunitySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$projectId': {
      id: '/tools/$projectId'
      path: '/tools/$projectId'
      fullPath: '/tools/$projectId'
      preLoaderRoute: typeof ToolsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/family': {
      id: '/settings/family'
      path: '/family'
      fullPath: '/settings/family'
      preLoaderRoute: typeof SettingsFamilyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/add-event': {
      id: '/settings/add-event'
      path: '/add-event'
      fullPath: '/settings/add-event'
      preLoaderRoute: typeof SettingsAddEventRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/learner/$id': {
      id: '/learner/$id'
      path: '/learner/$id'
      fullPath: '/learner/$id'
      preLoaderRoute: typeof LearnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/weaving': {
      id: '/lab/weaving'
      path: '/weaving'
      fullPath: '/lab/weaving'
      preLoaderRoute: typeof LabWeavingRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/visual': {
      id: '/lab/visual'
      path: '/visual'
      fullPath: '/lab/visual'
      preLoaderRoute: typeof LabVisualRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/stations': {
      id: '/lab/stations'
      path: '/stations'
      fullPath: '/lab/stations'
      preLoaderRoute: typeof LabStationsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/states': {
      id: '/lab/states'
      path: '/states'
      fullPath: '/lab/states'
      preLoaderRoute: typeof LabStatesRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/start': {
      id: '/lab/start'
      path: '/start'
      fullPath: '/lab/start'
      preLoaderRoute: typeof LabStartRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/routine': {
      id: '/lab/routine'
      path: '/routine'
      fullPath: '/lab/routine'
      preLoaderRoute: typeof LabRoutineRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/participations': {
      id: '/lab/participations'
      path: '/participations'
      fullPath: '/lab/participations'
      preLoaderRoute: typeof LabParticipationsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/community': {
      id: '/lab/community'
      path: '/community'
      fullPath: '/lab/community'
      preLoaderRoute: typeof LabCommunityRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/ai': {
      id: '/lab/ai'
      path: '/ai'
      fullPath: '/lab/ai'
      preLoaderRoute: typeof LabAiRouteImport
      parentRoute: typeof LabRoute
    }
    '/activities/options': {
      id: '/activities/options'
      path: '/activities/options'
      fullPath: '/activities/options'
      preLoaderRoute: typeof ActivitiesOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/my-day': {
      id: '/activities/my-day'
      path: '/activities/my-day'
      fullPath: '/activities/my-day'
      preLoaderRoute: typeof ActivitiesMyDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/level': {
      id: '/activities/level'
      path: '/activities/level'
      fullPath: '/activities/level'
      preLoaderRoute: typeof ActivitiesLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/browse': {
      id: '/activities/browse'
      path: '/activities/browse'
      fullPath: '/activities/browse'
      preLoaderRoute: typeof ActivitiesBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$category': {
      id: '/activities/$category'
      path: '/activities/$category'
      fullPath: '/activities/$category'
      preLoaderRoute: typeof ActivitiesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-routine': {
      id: '/_authenticated/my-routine'
      path: '/my-routine'
      fullPath: '/my-routine'
      preLoaderRoute: typeof AuthenticatedMyRoutineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/active-participations': {
      id: '/_authenticated/active-participations'
      path: '/active-participations'
      fullPath: '/active-participations'
      preLoaderRoute: typeof AuthenticatedActiveParticipationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/event/$eventId': {
      id: '/lab/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/lab/event/$eventId'
      preLoaderRoute: typeof LabEventEventIdRouteImport
      parentRoute: typeof LabRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedActiveParticipationsRoute: typeof AuthenticatedActiveParticipationsRoute
  AuthenticatedMyRoutineRoute: typeof AuthenticatedMyRoutineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedActiveParticipationsRoute:
    AuthenticatedActiveParticipationsRoute,
  AuthenticatedMyRoutineRoute: AuthenticatedMyRoutineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LabRouteChildren {
  LabAiRoute: typeof LabAiRoute
  LabCommunityRoute: typeof LabCommunityRoute
  LabParticipationsRoute: typeof LabParticipationsRoute
  LabRoutineRoute: typeof LabRoutineRoute
  LabStartRoute: typeof LabStartRoute
  LabStatesRoute: typeof LabStatesRoute
  LabStationsRoute: typeof LabStationsRoute
  LabVisualRoute: typeof LabVisualRoute
  LabWeavingRoute: typeof LabWeavingRoute
  LabIndexRoute: typeof LabIndexRoute
  LabEventEventIdRoute: typeof LabEventEventIdRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabAiRoute: LabAiRoute,
  LabCommunityRoute: LabCommunityRoute,
  LabParticipationsRoute: LabParticipationsRoute,
  LabRoutineRoute: LabRoutineRoute,
  LabStartRoute: LabStartRoute,
  LabStatesRoute: LabStatesRoute,
  LabStationsRoute: LabStationsRoute,
  LabVisualRoute: LabVisualRoute,
  LabWeavingRoute: LabWeavingRoute,
  LabIndexRoute: LabIndexRoute,
  LabEventEventIdRoute: LabEventEventIdRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface SettingsRouteChildren {
  SettingsAddEventRoute: typeof SettingsAddEventRoute
  SettingsFamilyRoute: typeof SettingsFamilyRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAddEventRoute: SettingsAddEventRoute,
  SettingsFamilyRoute: SettingsFamilyRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CommunitySupportRoute: CommunitySupportRoute,
  EducationSupportRoute: EducationSupportRoute,
  HelpMeChooseRoute: HelpMeChooseRoute,
  LabRoute: LabRouteWithChildren,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  ParticipationGuideRoute: ParticipationGuideRoute,
  ReminderRoute: ReminderRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ActivitiesCategoryRoute: ActivitiesCategoryRoute,
  ActivitiesBrowseRoute: ActivitiesBrowseRoute,
  ActivitiesLevelRoute: ActivitiesLevelRoute,
  ActivitiesMyDayRoute: ActivitiesMyDayRoute,
  ActivitiesOptionsRoute: ActivitiesOptionsRoute,
  LearnerIdRoute: LearnerIdRoute,
  ToolsProjectIdRoute: ToolsProjectIdRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
